version: "3.9"

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run
    restart: unless-stopped
    network_mode: bridge
